### ISSUE TITLE
Diff any two queries

### ISSUE THREAD

**Issue by homam** [Pipend/pipe#1]
Make diff work with any two queries:

```
/diff?left=pg8ilvv&right=pg8il32
```

It can be used to compare revisions to the same branch and also comparing queries from different branch.

**Comment by furqanZafar** [comment]
the api route for diff already contains left only right needs to be specified in the query string i.e:
```
# displays the diff between its remote and local version
http://localhost:4081/branches/pg6w7uI/queries/pg6GzOh/tree 

# displays the diff between 2 queries where left is pg6GzOh & right is pg8il32 
http://localhost:4081/branches/pg6w7uI/queries/pg6GzOh/tree?right= pg8il32
```
